version: "3"
services:
  rust-dev:
    build:
      context: ".devcontainer"
    volumes:
      - .:/workspace:cached
      - "${HOME}/.kube/config:/home/vscode/.kube/config:ro"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    command: /bin/sh -c "while sleep 1000; do :; done"