# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.166.1/containers/rust/.devcontainer/base.Dockerfile

FROM mcr.microsoft.com/vscode/devcontainers/rust:0-1

RUN  sudo apt-get update && sudo apt-get install -y yarn wget gnupg2 graphviz openjdk-11-jdk pkg-config libssl-dev
USER vscode